[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; frame-ancestors 'none';"

[[edge_functions]]
  path = "/edge-hello"
  function = "edge-hello"
